/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chess_application_services_NativeEngineService */

#ifndef _Included_com_chess_application_services_NativeEngineService
#define _Included_com_chess_application_services_NativeEngineService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chess_application_services_NativeEngineService
 * Method:    test_java_interface
 * Signature: (Lcom/chess/application/controller/model/Piece;)Lcom/chess/application/controller/model/Piece;
 */
JNIEXPORT jobject JNICALL Java_com_chess_application_services_NativeEngineService_test_1java_1interface
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
